#![cfg(feature = "proptest-support")]

use na::{Matrix2, Matrix4x2, U3, U4};

#[test]
fn simple_qr() {
    #[rustfmt::skip]
    let a = Matrix4x2::new(
        -0.8943285241224914 ,  0.12787800716234649,
        -0.37320804072796987,  0.21338804264385058,
         0.                 , -0.2456767687354977 ,
         0.2456767687354977 ,  0.                 );
    let qr = a.qr();
    // The reference values were generated by converting the input
    // to the form `m * 2 ^ e` for integers m and e. This was then used to
    // obtain the QR decomposition without rounding errors. The result was
    // converted back to f64.
    #[rustfmt::skip]
    let r_ref = Matrix2::new(
        0.99973237689865724, -0.19405501632841561,
        0.                 , -0.2908383860381578);
    assert_relative_eq!(qr.r(), r_ref);

    #[rustfmt::skip]
    let q_ref = Matrix4x2::new(
        -0.89456793116659196,  0.15719172406996297,
        -0.3733079465583837 , -0.48461884587835711,
         0.                 ,  0.8447191998351451,
         0.24574253511487697, -0.1639658791740342);
    assert_relative_eq!(qr.q(), q_ref);
}

#[test]
fn q_columns() {
    let a = Matrix4x2::new(0., 1., 3., 3., 1., 1., 2., 1.);
    let qr = a.qr();

    // The full `Q` is orthogonal, and its first columns are the ones of `q()`.
    let q_full = qr.q_columns(U4);
    assert!(q_full.is_orthogonal(1.0e-15));
    assert_relative_eq!(q_full.fixed_columns::<2>(0).into_owned(), qr.q());
    assert_relative_eq!(qr.q_columns(U3), q_full.fixed_columns::<3>(0).into_owned());
}

#[test]
#[should_panic]
fn q_columns_panic() {
    let _ = Matrix2::<f64>::zeros().qr().q_columns(U3);
}

#[test]
fn qr_zero_matrix() {
    // All the reflections are the identity, so `Q` is the identity too.
    let qr = Matrix4x2::<f64>::zeros().qr();

    assert_eq!(qr.r(), Matrix2::zeros());
    assert!(qr.q_columns(U4).is_identity(1.0e-15));
    assert!(qr.q().is_orthogonal(1.0e-15));
}

macro_rules! gen_tests(
    ($module: ident, $scalar: expr, $scalar_type: ty) => {
        mod $module {
            use na::{DMatrix, DVector, Dyn, Matrix4x3, Vector4};
            use std::cmp;
            #[allow(unused_imports)]
            use crate::core::helper::{RandScalar, RandComplex};
            use crate::proptest::*;
            use proptest::{prop_assert, proptest};

            proptest! {
                #[test]
                fn qr(m in dmatrix_($scalar)) {
                    let qr = m.clone().qr();
                    let q  = qr.q();
                    let r  = qr.r();

                    prop_assert!(relative_eq!(m, &q * r, epsilon = 1.0e-9));
                    prop_assert!(q.is_orthogonal(1.0e-13));
                }

                #[test]
                fn qr_static_5_3(m in matrix5x3_($scalar)) {
                    let qr = m.qr();
                    let q  = qr.q();
                    let r  = qr.r();

                    prop_assert!(relative_eq!(m, q * r, epsilon = 1.0e-9));
                    prop_assert!(q.is_orthogonal(1.0e-13));
                }

                #[test]
                fn qr_static_3_5(m in matrix3x5_($scalar)) {
                    let qr = m.qr();
                    let q  = qr.q();
                    let r  = qr.r();

                    prop_assert!(relative_eq!(m, q * r, epsilon = 1.0e-9));
                    prop_assert!(q.is_orthogonal(1.0e-13));
                }

                #[test]
                fn qr_static_square(m in matrix4_($scalar)) {
                    let qr = m.qr();
                    let q  = qr.q();
                    let r  = qr.r();

                    prop_assert!(relative_eq!(m, q * r, epsilon = 1.0e-9));
                    prop_assert!(q.is_orthogonal(1.0e-13));
                }

                #[test]
                fn qr_q_columns(m in dmatrix_($scalar)) {
                    let nrows = m.nrows();
                    let q = m.qr().q_columns(Dyn(nrows));

                    prop_assert!(q.is_orthogonal(1.0e-13));
                }

                #[test]
                fn qr_q_tr_mul(m in dmatrix_($scalar)) {
                    let nrows = m.nrows();
                    let qr = m.qr();
                    let b = DMatrix::<$scalar_type>::new_random(nrows, 3).map(|e| e.0);

                    let mut q_tr_b = b.clone();
                    qr.q_tr_mul(&mut q_tr_b);

                    let q = qr.q_columns(Dyn(nrows));
                    prop_assert!(relative_eq!(q_tr_b, q.adjoint() * b, epsilon = 1.0e-9));
                }

                #[test]
                fn qr_solve(n in PROPTEST_MATRIX_DIM, nb in PROPTEST_MATRIX_DIM) {
                    let m  = DMatrix::<$scalar_type>::new_random(n, n).map(|e| e.0);

                    let qr = m.clone().qr();
                    let b1 = DVector::<$scalar_type>::new_random(n).map(|e| e.0);
                    let b2 = DMatrix::<$scalar_type>::new_random(n, nb).map(|e| e.0);

                    if qr.is_invertible() {
                        let sol1 = qr.solve(&b1).unwrap();
                        let sol2 = qr.solve(&b2).unwrap();

                        prop_assert!(relative_eq!(&m * sol1, b1, epsilon = 1.0e-6));
                        prop_assert!(relative_eq!(&m * sol2, b2, epsilon = 1.0e-6));
                    }
                }

                #[test]
                fn qr_solve_static(m in matrix4_($scalar)) {
                     let qr = m.qr();
                     let b1 = Vector4::<$scalar_type>::new_random().map(|e| e.0);
                     let b2 = Matrix4x3::<$scalar_type>::new_random().map(|e| e.0);

                     if qr.is_invertible() {
                         let sol1 = qr.solve(&b1).unwrap();
                         let sol2 = qr.solve(&b2).unwrap();

                         prop_assert!(relative_eq!(m * sol1, b1, epsilon = 1.0e-6));
                         prop_assert!(relative_eq!(m * sol2, b2, epsilon = 1.0e-6));
                     }
                }

                #[test]
                fn qr_inverse(n in PROPTEST_MATRIX_DIM) {
                    let n = cmp::max(1, cmp::min(n, 15)); // To avoid slowing down the test too much.
                    let m = DMatrix::<$scalar_type>::new_random(n, n).map(|e| e.0);

                    if let Some(m1) = m.clone().qr().try_inverse() {
                        let id1 = &m  * &m1;
                        let id2 = &m1 * &m;

                        prop_assert!(id1.is_identity(1.0e-5));
                        prop_assert!(id2.is_identity(1.0e-5));
                    }
                }

                #[test]
                fn qr_inverse_static(m in matrix4_($scalar)) {
                    let qr = m.qr();

                    if let Some(m1) = qr.try_inverse() {
                        let id1 = &m  * &m1;
                        let id2 = &m1 * &m;

                        prop_assert!(id1.is_identity(1.0e-5));
                        prop_assert!(id2.is_identity(1.0e-5));
                    }
                }
            }
        }
    }
);

gen_tests!(complex, complex_f64(), RandComplex<f64>);
gen_tests!(f64, PROPTEST_F64, RandScalar<f64>);
