pub fn vec< 3, T, Q > 	cross (qua< T, Q > const &q, vec< 3, T, Q > const &v)
pub fn vec< 3, T, Q > 	cross (vec< 3, T, Q > const &v, qua< T, Q > const &q)
pub fn T 	extractRealComponent (qua< T, Q > const &q)
pub fn qua< T, Q > 	fastMix (qua< T, Q > const &x, qua< T, Q > const &y, T const &a)
pub fn qua< T, Q > 	intermediate (qua< T, Q > const &prev, qua< T, Q > const &curr, qua< T, Q > const &next)
pub fn T 	length2 (qua< T, Q > const &q)
pub fn qua< T, Q > 	quat_identity ()
pub fn vec< 3, T, Q > 	rotate (qua< T, Q > const &q, vec< 3, T, Q > const &v)
pub fn vec< 4, T, Q > 	rotate (qua< T, Q > const &q, vec< 4, T, Q > const &v)
pub fn qua< T, Q > 	rotation (vec< 3, T, Q > const &orig, vec< 3, T, Q > const &dest)
pub fn qua< T, Q > 	shortMix (qua< T, Q > const &x, qua< T, Q > const &y, T const &a)
pub fn qua< T, Q > 	squad (qua< T, Q > const &q1, qua< T, Q > const &q2, qua< T, Q > const &s1, qua< T, Q > const &s2, T const &h)
pub fn mat< 3, 3, T, Q > 	toMat3 (qua< T, Q > const &x)
pub fn mat< 4, 4, T, Q > 	toMat4 (qua< T, Q > const &x)
pub fn qua< T, Q > 	toQuat (mat< 3, 3, T, Q > const &x)
pub fn qua< T, Q > 	toQuat (mat< 4, 4, T, Q > const &x)
