pub fn mat< 3, 3, T, Q > 	proj2D (mat< 3, 3, T, Q > const &m, vec< 3, T, Q > const &normal)
pub fn mat< 4, 4, T, Q > 	proj3D (mat< 4, 4, T, Q > const &m, vec< 3, T, Q > const &normal)
pub fn mat< 4, 4, T, Q > 	scaleBias (T scale, T bias)
pub fn mat< 4, 4, T, Q > 	scaleBias (mat< 4, 4, T, Q > const &m, T scale, T bias)
pub fn mat< 3, 3, T, Q > 	shearX2D (mat< 3, 3, T, Q > const &m, T y)
pub fn mat< 4, 4, T, Q > 	shearX3D (mat< 4, 4, T, Q > const &m, T y, T z)
pub fn mat< 3, 3, T, Q > 	shearY2D (mat< 3, 3, T, Q > const &m, T x)
pub fn mat< 4, 4, T, Q > 	shearY3D (mat< 4, 4, T, Q > const &m, T x, T z)
pub fn mat< 4, 4, T, Q > 	shearZ3D (mat< 4, 4, T, Q > const &m, T x, T y)